- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - openstack-python3-wallaby-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
      - periodic-jobs-with-oslo-master
